//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ArchiveTags struct {
	ArchiveID int32
	TagID     int32
	CreatedAt time.Time
}
