//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type CollectionArchive struct {
	CollectionID int32 `sql:"primary_key"`
	ArchiveID    int32 `sql:"primary_key"`
	Order        int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
