//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Tags struct {
	ID          int32 `sql:"primary_key"`
	Namespace   string
	Name        string
	DisplayName *string
	Hidden      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
