//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type UserReadHistory struct {
	UserID     string `sql:"primary_key"`
	ArchiveID  int32  `sql:"primary_key"`
	LastPage   int32
	StartPage  int32
	MaxPage    int32
	StartedAt  time.Time
	LastReadAt time.Time
	FinishedAt *time.Time
}
