ALTER TABLE archives DROP COLUMN slug;
ALTER TABLE archives RENAME COLUMN hash TO key;
ALTER TABLE archives ALTER COLUMN key TYPE VARCHAR(64);
ALTER TABLE archives ALTER COLUMN size DROP NOT NULL;
ALTER TABLE archives ALTER COLUMN released_at DROP NOT NULL;
ALTER TABLE archives ALTER COLUMN released_at DROP DEFAULT;