name: Compile to binary

on:
  push:
    branches: 'compile-action'

jobs:
  # https://github.com/shadps4-emu/shadPS4/blob/main/.github/workflows/build.yml
  get-info:
    runs-on: [self-hosted, Linux]
    outputs:
      date: ${{ steps.vars.outputs.date }}
      hash: ${{ steps.vars.outputs.hash }}
      version: ${{ steps.vars.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Get date and git hash
        id: vars
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "version=`(jq -r '.version' package.json)`" >> $GITHUB_OUTPUT

  # linux-amd64:
  #   runs-on: [self-hosted, Linux, X64]
  #   needs: get-info
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Compile Faccina
  #       run: ./build.sh
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: faccina-linux-amd64-${{ needs.get-info.outputs.hash }}
  #         path: faccina

  linux-arm64:
    runs-on: [self-hosted, Linux, AR64]
    needs: get-info
    steps:
      - uses: actions/checkout@v4
      - name: Compile Faccina
        run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: faccina-linux-arm64-${{ needs.get-info.outputs.hash }}
          path: faccina

  # darwin-arm64:
  #   runs-on: [self-hosted, macOS, ARM64]
  #   needs: get-info
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Compile Faccina
  #       run: ./build.sh
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: faccina-darwin-arm64-${{ needs.get-info.outputs.hash }}
  #         path: faccina
