name: Compile to binary

on:
  push:
    branches: 'compile-action'

jobs:
  linux-amd64:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v4
      - name: Build Faccina
        run: ./build.sh
      - name: Package binary
        run: tar -czf faccina-linux-amd64.tar.gz faccina
      - uses: actions/upload-artifact@v4
        with:
          name: faccina-linux-amd64
          path: faccina-linux-amd64.tar.gz
